### ISSUE TITLE
SIGNAL Received when chat_info command issued.

### ISSUE THREAD

**Issue by jonnywilliamson** [vysheng/tg#510]
###For info using the latest Test branch build.

Getting a crash each time I try a chat_info command.

```
vagrant@homestead:~/CodeProjects/test$ /home/vagrant/telegram/bin/telegram-cli -k /home/vagrant/telegram/tg-server.pub -WS /tmp/tg.sck

Telegram-cli version 1.2.0, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
Telegram-cli uses libtgl version 2.0.0
I: config dir=[/home/vagrant/.telegram-cli]
Chat Test group please ignore updated photo admin members

> SIGNAL received
h/home/vagrant/telegram/bin/telegram-cli(print_backtrace+0x2f)[0x46826f]
/home/vagrant/telegram/bin/telegram-cli(termination_signal_handler+0x64)[0x468304]
/lib/x86_64-linux-gnu/libc.so.6(+0x36eb0)[0x7fa8f2530eb0]
/home/vagrant/telegram/bin/telegram-cli(tgls_free_photo+0x14)[0x48fe34]
/home/vagrant/telegram/bin/telegram-cli[0x497137]
/home/vagrant/telegram/bin/telegram-cli[0x497aae]
/home/vagrant/telegram/bin/telegram-cli(bl_do_chat_new+0x49e)[0x499e9e]
/home/vagrant/telegram/bin/telegram-cli(tglf_fetch_chat_full_new+0x64)[0x493524]
/home/vagrant/telegram/bin/telegram-cli(tglf_fetch_alloc_chat_full_new+0x4e)[0x49360e]
/home/vagrant/telegram/bin/telegram-cli[0x47f375]
/home/vagrant/telegram/bin/telegram-cli(tglq_query_result+0x10f)[0x4845cf]
/home/vagrant/telegram/bin/telegram-cli[0x47d5ee]
/home/vagrant/telegram/bin/telegram-cli[0x49d99b]
/usr/lib/x86_64-linux-gnu/libevent-2.0.so.5(event_base_loop+0x7fc)[0x7fa8f354aa0c]
/home/vagrant/telegram/bin/telegram-cli(net_loop+0xa4)[0x469444]
/home/vagrant/telegram/bin/telegram-cli(loop+0x17f)[0x46a7ff]
/home/vagrant/telegram/bin/telegram-cli(main+0x291)[0x466bc1]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7fa8f251bec5]
/home/vagrant/telegram/bin/telegram-cli[0x466cbf]
```

**Comment by vysheng** [comment]
should be fixed by last commit.

**Comment by fwolf** [comment]
@vysheng not work again, version cf6cb90


	Telegram-cli version 1.3.3, Copyright (C) 2013-2015 Vitaly Valtman
	Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
	This is free software, and you are welcome to redistribute it
	under certain conditions; type `show_license' for details.
	Telegram-cli uses libtgl version 2.0.3
	Telegram-cli includes software developed by the OpenSSL Project
	for use in the OpenSSL Toolkit. (http://www.openssl.org/)
	Telegram-cli uses libpython version 2.7.6
	I: config dir=[/home/fwolf/.telegram-cli]
	> SIGNAL received
	hbin/telegram-cli(print_backtrace+0x20)[0x46f5b0]
	bin/telegram-cli(termination_signal_handler+0x64)[0x46f634]
	/lib/x86_64-linux-gnu/libc.so.6(+0x36d40)[0x7ff4986f0d40]
	/usr/lib/x86_64-linux-gnu/libevent-2.0.so.5(event_add+0x21)[0x7ff49a091141]
	bin/telegram-cli(tgln_write_out+0x14e)[0x4b3e2e]
	bin/telegram-cli(tglmp_encrypt_send_message+0x22d)[0x4900dd]
	bin/telegram-cli[0x495424]
	/usr/lib/x86_64-linux-gnu/libevent-2.0.so.5(event_base_loop+0x754)[0x7ff49a091f2
	4]
	bin/telegram-cli(net_loop+0xa4)[0x4706f4]
	bin/telegram-cli(loop+0x195)[0x471a05]
	bin/telegram-cli(main+0x2d3)[0x46dec3]
	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7ff4986dbec5]
	bin/telegram-cli[0x46dfd3]

**Comment by vcaldo** [comment]
@vysheng Any update on this? Still getting the <SIGNAL received> when using chat_info.
I'm using the latest test branch.

**Comment by authorized13** [comment]
What time do you want me to be there tomorrow morning and then you can sign
signal me let me know its you and I'll get in the car and we can go to
California...when and where exactly and I will so be there..

**Comment by authorized13** [comment]
---------- Forwarded message ----------
From: ca820132@gmail.com
Date: Jan 29, 2016 8:28 PM
Subject: Fwd: Re:
To: <orders@textnow.com>
Cc:

---------- Forwarded message ----------
From: "Chris Allen" <ca820132@gmail.com>
Date: Jan 3, 2016 5:48 PM
Subject: Re:
To: "Chris Allen" <ca820132@gmail.com>
Cc:

God whatever comes my way...I WILL TRUST YOU TO WORK EVERYTHING FOR GOOD!!!
My deepest cry help me make it right!!! I want to send your kids to Church
Camps Father!!! YOU HOLD MY DREAMS IN YOUR HANDS...I TRUST YOU!!!

**Comment by authorized13** [comment]
http://www.google.com/aclk?sa=l&ai=CBj3Nd4CtVv2HE824-QPApovwCsKXttwG8uDNuccC54OenGsIABABIJfgvAtgya7fhsijkBmgAbiPlO4DyAEBqgQlT9AsVOohZpOKsCTVayGrTVQ_fIVq5tLi0BDv7e6okqGHb9J5aNgGAoAHsPDrEZAHAagHpr4b2AcB&sig=AOD64_0rEFkQJUOE-NiwXpRPiz6592vbXg&clui=0&ved=0ahUKEwiFuvDrjtPKAhVL5mMKHWZhAbcQ0QwICg&adurl=http://tracker.marinsm.com/rd%3Fcid%3D268861bw43658%26msid%3DsqTZReU5V_dm%26creative%3D87899950706%26pmt%3Db%26pkw%3D%252Bchase%2520%252Bbank%2520%252Baccount%26lp%3Dhttps://ad.doubleclick.net/ddm/clk/295507458%3B107969704%3Bx%3Bu%3D87899950706%7CqTZReU5V_dm%7Cb%7C%252Bchase%2520%252Bbank%2520%252Baccount%7C158-544-1378%7C263906066%7C15395720906%3Fhttps://www.chase.com/checking/offer/get-coupon-bandujo-combo-1.html%3F%26jp_cmp%3Dcc/Homepage%2BTest%2B-%2BBrand%2B-%2BBMM/sea/qTZReU5V/Chase%2B-%2BAccount%26kwdID%3DqTZReU5V_dm%26adgrpID%3D87899950706

**Comment by authorized13** [comment]
There is an app called confide I sent you a link check it out
